namespace Sanes.Application.Dashboard.DTOs;

public class FinancialDashboardSummaryResponse
{
    /*
     * Current portfolio.
     */
    public int ActiveLoansCount { get; set; }

    public int ActiveClientsCount { get; set; }

    /*
     * Origination history.
     */
    public decimal PrincipalOriginated { get; set; }

    public decimal ContractualAmountOriginated { get; set; }

    public decimal GrossContractualInterest { get; set; }

    /*
     * Contractual reductions generated by
     * early settlements.
     */
    public decimal EarlySettlementDiscounts { get; set; }

    public decimal NetContractualInterest { get; set; }

    /*
     * Current outstanding portfolio.
     *
     * ContractualBalanceOutstanding represents
     * "dinero en calle".
     */
    public decimal ContractualBalanceOutstanding { get; set; }

    public decimal LateFeeBalanceOutstanding { get; set; }

    public decimal TotalOutstanding { get; set; }

    /*
     * Actual cash received historically.
     */
    public decimal CashCollected { get; set; }

    public decimal ContractualCashCollected { get; set; }

    public decimal LateFeesCollected { get; set; }

    /*
     * Delinquency.
     */
    public int OverdueLoansCount { get; set; }

    public decimal OverdueContractualAmount { get; set; }

    /*
     * OverdueContractualAmount /
     * ContractualBalanceOutstanding * 100
     */
    public decimal DelinquencyRate { get; set; }
}