using Sanes.Application.Common.Persistence;
using Sanes.Application.LateFees.Services;
using Sanes.Application.Loans.Repositories;
using Sanes.Application.Payments.DTOs;
using Sanes.Application.Payments.Repositories;
using Sanes.Domain.Entities;
using Sanes.Domain.Enums;

namespace Sanes.Application.Payments.Services;

public class PaymentReversalService
    : IPaymentReversalService
{
    private readonly IPaymentRepository
        _paymentRepository;

    private readonly IPaymentReversalRepository
        _paymentReversalRepository;

    private readonly IPaymentAllocationRepository
        _paymentAllocationRepository;

    private readonly ILoanRepository
        _loanRepository;

    private readonly ILoanBalanceAdjustmentRepository
        _loanBalanceAdjustmentRepository;

    private readonly ILateFeeBalanceService
        _lateFeeBalanceService;

    private readonly ITransactionRunner
        _transactionRunner;

    public PaymentReversalService(
        IPaymentRepository paymentRepository,
        IPaymentReversalRepository paymentReversalRepository,
        IPaymentAllocationRepository paymentAllocationRepository,
        ILoanRepository loanRepository,
        ILoanBalanceAdjustmentRepository
            loanBalanceAdjustmentRepository,
        ILateFeeBalanceService lateFeeBalanceService,
        ITransactionRunner transactionRunner)
    {
        _paymentRepository =
            paymentRepository;

        _paymentReversalRepository =
            paymentReversalRepository;

        _paymentAllocationRepository =
            paymentAllocationRepository;

        _loanRepository =
            loanRepository;

        _loanBalanceAdjustmentRepository =
            loanBalanceAdjustmentRepository;

        _lateFeeBalanceService =
            lateFeeBalanceService;

        _transactionRunner =
            transactionRunner;
    }

    public Task<PaymentReversalResponse> ReverseAsync(
        Guid tenantId,
        Guid appUserId,
        Guid paymentId,
        PaymentReversalRequest request,
        CancellationToken cancellationToken = default)
    {
        ValidateIdentifiers(
            tenantId,
            appUserId,
            paymentId);

        ArgumentNullException.ThrowIfNull(
            request);

        var reason =
            NormalizeReason(
                request.Reason);

        return _transactionRunner.ExecuteAsync(
            transactionCancellationToken =>
                ReverseCoreAsync(
                    tenantId,
                    appUserId,
                    paymentId,
                    reason,
                    transactionCancellationToken),
            cancellationToken);
    }

    private async Task<PaymentReversalResponse>
        ReverseCoreAsync(
            Guid tenantId,
            Guid appUserId,
            Guid paymentId,
            string reason,
            CancellationToken cancellationToken)
    {
        /*
         * Se obtiene como tracked porque el reverso y
         * cualquier cambio en Loan deben formar parte
         * de la misma transacción.
         */
        var payment =
            await _paymentRepository
                .GetByIdForUpdateAsync(
                    tenantId,
                    paymentId,
                    cancellationToken);

        if (payment is null)
        {
            throw new InvalidOperationException(
                "Payment not found or does not belong to the specified tenant.");
        }

        if (payment.Reversal is not null)
        {
            throw new InvalidOperationException(
                "The payment has already been reversed.");
        }

        /*
         * Una liquidación anticipada también genera
         * LoanBalanceAdjustment y EarlySettlement.
         *
         * Reversar solamente el Payment dejaría esos
         * registros financieros vigentes y rompería
         * la consistencia de la liquidación.
         */
        if (payment.EarlySettlement is not null)
        {
            throw new InvalidOperationException(
                "Payments generated by an early settlement cannot be reversed from the payment reversal module.");
        }

        /*
         * Solamente permitimos reversar el último pago
         * financiero vigente del préstamo.
         *
         * Esto evita tener que redistribuir allocations
         * pertenecientes a pagos posteriores.
         */
        var latestEffectivePayment =
            await _paymentRepository
                .GetLatestEffectiveByLoanAsync(
                    tenantId,
                    payment.LoanId,
                    cancellationToken);

        if (latestEffectivePayment is null ||
            latestEffectivePayment.Id != payment.Id)
        {
            throw new InvalidOperationException(
                "Only the latest effective payment of the loan can be reversed.");
        }

        var loan =
            await _loanRepository
                .GetByIdForUpdateAsync(
                    tenantId,
                    payment.LoanId,
                    cancellationToken);

        if (loan is null)
        {
            throw new InvalidOperationException(
                "The loan associated with the payment could not be found.");
        }

        var now =
            DateTime.UtcNow;

        var reversal =
            new PaymentReversal
            {
                TenantId =
                    tenantId,

                PaymentId =
                    payment.Id,

                Payment =
                    payment,

                ReversedByAppUserId =
                    appUserId,

                Reason =
                    reason,

                CreatedAt =
                    now
            };

        payment.Reversal =
            reversal;

        await _paymentReversalRepository
            .AddAsync(
                reversal,
                cancellationToken);

        /*
         * Debemos persistir el PaymentReversal dentro
         * de la transacción antes de recalcular.
         *
         * Las consultas financieras filtran mediante:
         *
         *     Payment.Reversal == null
         *
         * por lo que PostgreSQL necesita ver el reverso
         * dentro de la transacción actual.
         *
         * Si posteriormente ocurre cualquier error,
         * ITransactionRunner revierte toda la operación.
         */
        await _paymentReversalRepository
            .SaveChangesAsync(
                cancellationToken);

        var totalAppliedToLoan =
            await _paymentAllocationRepository
                .GetTotalAppliedToLoanAsync(
                    tenantId,
                    loan.Id,
                    cancellationToken);

        var contractualAdjustments =
            await _loanBalanceAdjustmentRepository
                .GetTotalReductionsByLoanAsync(
                    tenantId,
                    loan.Id,
                    cancellationToken);

        var totalAmount =
            loan.InstallmentAmount *
            loan.TotalInstallments;

        var contractualBalance =
            totalAmount
            - totalAppliedToLoan
            - contractualAdjustments;

        if (contractualBalance < 0m)
        {
            contractualBalance = 0m;
        }

        var lateFeeBalance =
            await _lateFeeBalanceService
                .GetOutstandingBalanceAsync(
                    tenantId,
                    loan.Id,
                    cancellationToken);

        /*
         * Cancelled es una decisión administrativa
         * independiente del pago.
         *
         * Un reverso nunca reactiva automáticamente
         * un préstamo cancelado.
         */
        if (loan.Status != LoanStatus.Cancelled)
        {
            loan.Status =
                contractualBalance == 0m &&
                lateFeeBalance == 0m
                    ? LoanStatus.Paid
                    : LoanStatus.Active;
        }

        /*
         * Reconstruimos NextPaymentDate desde cero
         * utilizando únicamente las allocations
         * contractuales todavía efectivas.
         *
         * No intentamos "restar una frecuencia" porque
         * el pago reversado puede haber sido parcial,
         * destinado solo a mora o haber completado
         * múltiples cuotas.
         */
        loan.NextPaymentDate =
            CalculateNextPaymentDate(
                loan,
                totalAppliedToLoan);

        loan.UpdatedAt =
            now;

        /*
         * PaymentReversal ya se insertó dentro de la
         * transacción. Este SaveChanges persiste ahora
         * el nuevo estado financiero del Loan.
         */
        await _paymentReversalRepository
            .SaveChangesAsync(
                cancellationToken);

        return new PaymentReversalResponse
        {
            Id =
                reversal.Id,

            PaymentId =
                payment.Id,

            LoanId =
                payment.LoanId,

            Amount =
                payment.Amount,

            PaymentDate =
                payment.PaymentDate,

            PaymentType =
                payment.PaymentType,

            ReversedByAppUserId =
                reversal.ReversedByAppUserId,

            Reason =
                reversal.Reason,

            CreatedAt =
                reversal.CreatedAt
        };
    }

    private static DateTime CalculateNextPaymentDate(
        Loan loan,
        decimal totalAppliedToLoan)
    {
        if (loan.InstallmentAmount <= 0m)
        {
            throw new InvalidOperationException(
                "Loan installment amount must be greater than zero.");
        }

        var completedInstallments =
            (int)Math.Floor(
                totalAppliedToLoan /
                loan.InstallmentAmount);

        /*
         * Nunca permitimos que errores históricos
         * produzcan una fecha más allá del contrato.
         */
        if (completedInstallments < 0)
        {
            completedInstallments = 0;
        }

        if (completedInstallments >
            loan.TotalInstallments)
        {
            completedInstallments =
                loan.TotalInstallments;
        }

        /*
         * Primera fecha de pago:
         *
         * StartDate + 1 frecuencia.
         *
         * Luego avanzamos una frecuencia adicional
         * por cada cuota equivalente completada.
         */
        var nextPaymentDate =
            AddFrequency(
                loan.StartDate,
                loan.PaymentFrequency);

        for (
            var i = 0;
            i < completedInstallments;
            i++)
        {
            nextPaymentDate =
                AddFrequency(
                    nextPaymentDate,
                    loan.PaymentFrequency);
        }

        return nextPaymentDate;
    }

    private static DateTime AddFrequency(
        DateTime date,
        PaymentFrequency frequency)
    {
        return frequency switch
        {
            PaymentFrequency.Daily =>
                date.AddDays(1),

            PaymentFrequency.Weekly =>
                date.AddDays(7),

            PaymentFrequency.Biweekly =>
                date.AddDays(14),

            PaymentFrequency.Monthly =>
                date.AddMonths(1),

            _ =>
                throw new InvalidOperationException(
                    "Invalid payment frequency.")
        };
    }

    private static string NormalizeReason(
        string? reason)
    {
        if (string.IsNullOrWhiteSpace(
                reason))
        {
            throw new InvalidOperationException(
                "A reversal reason is required.");
        }

        var normalized =
            reason.Trim();

        if (normalized.Length > 500)
        {
            throw new InvalidOperationException(
                "Reversal reason cannot exceed 500 characters.");
        }

        return normalized;
    }

    private static void ValidateIdentifiers(
        Guid tenantId,
        Guid appUserId,
        Guid paymentId)
    {
        if (tenantId == Guid.Empty)
        {
            throw new ArgumentException(
                "TenantId must be a valid identifier.",
                nameof(tenantId));
        }

        if (appUserId == Guid.Empty)
        {
            throw new ArgumentException(
                "AppUserId must be a valid identifier.",
                nameof(appUserId));
        }

        if (paymentId == Guid.Empty)
        {
            throw new ArgumentException(
                "PaymentId must be a valid identifier.",
                nameof(paymentId));
        }
    }
}